sudo: false

cache:
  directories:
    - '$HOME/.m2/repository'

language: java

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

after_success:
  - mvn clean test jacoco:report org.eluder.coveralls:coveralls-maven-plugin:report
